#!/usr/bin/env bash
#
# Configure (if needed) and run blog-server via docker-compose.
#
# If .env already exists, its values are used as-is and the server starts
# straight away — no prompts. If .env doesn't exist yet, you're prompted for
# each setting (with sensible defaults) and .env is written first.
#
# Usage:
#   ./scripts/run.sh               # first run: prompt then run. later runs: just run.
#   ./scripts/run.sh --reconfigure # re-prompt for everything, even if .env exists
#   ./scripts/run.sh --yes         # never prompt; use existing .env / defaults, then run
#   ./scripts/run.sh --configure   # only write .env, don't start the server

set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."

ENV_FILE=".env"
FORCE_SKIP_PROMPTS=false
RECONFIGURE=false
RUN_AFTER=true

for arg in "$@"; do
  case "$arg" in
    --yes|-y) FORCE_SKIP_PROMPTS=true ;;
    --reconfigure) RECONFIGURE=true ;;
    --configure) RUN_AFTER=false ;;
    *) echo "Unknown option: $arg" >&2; exit 1 ;;
  esac
done

ENV_EXISTS=false
if [[ -f "$ENV_FILE" ]]; then
  ENV_EXISTS=true
  # Load existing values so they become the defaults offered below (or the
  # values used outright, if we're not prompting).
  set -a
  # shellcheck disable=SC1090
  source "$ENV_FILE"
  set +a
fi

# Only touch .env if it doesn't exist yet, or the user explicitly asked to
# --reconfigure. Otherwise, leave it alone and just run.
if [[ "$ENV_EXISTS" == true && "$RECONFIGURE" == false ]]; then
  echo "Using existing $ENV_FILE (pass --reconfigure to change settings)"
else
  SKIP_PROMPTS="$FORCE_SKIP_PROMPTS"

  # name|default|prompt
  VARS=(
    "HOST_PORT|3110|Host port to expose the server on"
    "PORT|3000|Port the server listens on inside the container"
    "ENVIRONMENT|development|Environment name"
    "STAGING_MODE|false|Show unpublished articles in the recent feed (true/false)"
    "ALLOWED_ORIGINS||Comma-separated list of allowed CORS origins"
    "CONTENT_PATH|./content|Path to the content directory"
    "CONTENT_REPO||Remote git repo to clone content from (leave blank for local content)"
    "CONTENT_BRANCH||Branch to use for the remote content repo"
    "CONTENT_UPDATE_INTERVAL_SECONDS|300|How often (seconds) to pull content updates"
    "CONTENT_ASSET_DIR|images|Subdirectory holding static assets"
    "STATIC_ASSET_URL|images|URL prefix for image links"
    "TOPIC_FILE|README.md|Filename used to identify a topic within a directory"
    "BLOG_SITE_HOST||Base URL of the site to notify on content changes (leave blank to disable)"
    "BLOG_SITE_SECRET||Secret token for the revalidation request"
    "LOG_LEVEL|INFO|Log level (DEBUG, INFO, WARN, ERROR)"
    "LOG_FORMAT|json|Log format (json or text)"
    "SENTRY_DSN||Sentry DSN (leave blank to disable)"
    "OTEL_EXPORTER_OTLP_ENDPOINT||OTLP gRPC endpoint (leave blank to disable telemetry)"
    "OTEL_SERVICE_NAME|blog-server|Service name attached to telemetry"
  )

  # Bash 3 (macOS default) has no associative arrays, so we build the file
  # incrementally instead of collecting values into one.
  {
    echo "# Generated by scripts/run.sh on $(date)"
    for entry in "${VARS[@]}"; do
      IFS='|' read -r name fallback prompt <<< "$entry"
      current="${!name:-$fallback}"

      if [[ "$SKIP_PROMPTS" == true ]]; then
        value="$current"
      else
        read -rp "$prompt [$current]: " input
        value="${input:-$current}"
      fi

      echo "$name=$value"
    done
  } > "$ENV_FILE"

  echo "Wrote $ENV_FILE"
fi

if [[ "$RUN_AFTER" == true ]]; then
  docker compose up --build
fi
